Install OpenBLAS in final image
Previously, CVXOPT was unusable on the arm64 variant with this error:

    ImportError: liblapack.so.3: cannot open shared object file: No such file or directory

This makes sense because the CVXOPT installation instructions state that
BLAS and LAPACK are required¹ (these are provided by the OpenBLAS
package). In c1515608e17fc1f7d933854901ab2c81f51b696e, they were only
installed in the builder image since I did not realize they were
required during run time.

¹ https://cvxopt.org/install/#building-and-installing-from-source